sudo: required
services:
  - docker

before_install:
  - docker build -t yongoose/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true youngoose/react-test npm test

after_success:
  - docker build -t youngoose/multi-client ./client
  - docker build -t youngoose/multi-nginx ./nginx
  - docker build -t youngoose/multi-server ./server
  - docker build -t youngoose/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push yongoose/multi-client
  - docker push yongoose/multi-nginx
  - docker push yongoose/multi-server
  - docker push yongoose/multi-worker
